### ISSUE TITLE
希望能解除阅读页截图限制

### ISSUE THREAD

**Issue by a546109781** [xihan123/QDReadHook#1]
如题

**Comment by xihan123** [comment]
解除截图限制有相关的模块，而且阅读页截图我实在想不到能用到啥用途上，起点自带了分享本章，所以不予采用

**Comment by xihan123** [comment]
解除截图限制有相关的模块，而且阅读页截图我实在想不到能用到啥用途上，起点自带了分享本章，所以不予采用.
