### ISSUE TITLE
模块某功能会导致无法启动起点

### ISSUE THREAD

**Issue by zhongfly** [xihan123/QDReadHook#10]
miui 13(Android12)
lsposed 1.8.3 zygisk
起点 7.9.246(build 2693d1b7)
模块版本 1.1.6

未启用模块时 起点登录账号，应用正常打开
启用模块，且已经给于起点读取所有文件的权限(见下图)
![Screenshot_2022-09-12-11-49-10-824_com android permissioncontroller](https://user-images.githubusercontent.com/11155705/189570514-537081a7-e918-41a1-b41c-63b293313057.jpg)
![Screenshot_2022-09-12-11-48-44-494_com miui securitycenter](https://user-images.githubusercontent.com/11155705/189570521-f5ef1abf-2ba6-436e-bb39-b0a11a3edc5a.jpg)

启用模块后，打开起点，可以正常显示起点自己的开屏页，之后应该显示书架界面时，应用白屏，然后应用程序提示错误，见下图
![Screenshot_2022-09-12-11-52-33-139_com qidian QDReader](https://user-images.githubusercontent.com/11155705/189570851-51152c6f-7875-4ec1-b420-9a5e30ca6e96.jpg)

lsposed日志
[LSPosed_2022-09-12T11_52_46.297.zip](https://github.com/xihan123/QDReadHook/files/9544426/LSPosed_2022-09-12T11_52_46.297.zip)

内部存储中存在/QDReader/option.json文件，且内容正常可读

**Comment by xihan123** [comment]
你是覆盖安装升级的吗，清除起点数据或者重装模块就可以解决了

**Comment by zhongfly** [comment]
手动修改配置文件，禁用广告屏蔽功能后正常
```
"enableDisableAdv":false
```

**Comment by zhongfly** [comment]
> 你是覆盖安装升级的吗，清除起点数据或者重装模块就可以解决了

全新安装，之前没有安装这个模块

**Comment by xihan123** [comment]
> > 你是覆盖安装升级的吗，清除起点数据或者重装模块就可以解决了
> 
> 全新安装，之前没有安装这个模块

清除起点数据试过了没

**Comment by zhongfly** [comment]
> > > 你是覆盖安装升级的吗，清除起点数据或者重装模块就可以解决了
> > 
> > 
> > 全新安装，之前没有安装这个模块
> 
> 清除起点数据试过了没

正常了，启用屏蔽tx广告功能也不会白屏了

**Comment by xihan123** [comment]
> > > > 你是覆盖安装升级的吗，清除起点数据或者重装模块就可以解决了
> > > 
> > > 
> > > 全新安装，之前没有安装这个模块
> > 
> > 清除起点数据试过了没
> 
> 正常了，启用屏蔽tx广告功能也不会白屏了

这种情况一般是因为你起点本身就有缓存了，结果用了模块禁止加载GDT广告，所以闪退
