### ISSUE TITLE
无法使用"看小视频领奖励"功能

### ISSUE THREAD

**Issue by feilongproject** [xihan123/QDReadHook#11]
RT，在小说正文中，如果要看广告领取激励碎片的话，会报错
![Screenshot_2022-09-20-16-09-18-994_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/43880786/191203933-7886a0d2-afab-4568-85ed-819a17f403e5.jpg)

**Comment by xihan123** [comment]
因为你开启了禁用广告功能

**Comment by feilongproject** [comment]
> 因为你开启了禁用广告功能

已经关闭广告，但是在保存并重启后，设置会恢复默认，并且在LSPosed里面有疑似报错
```
[ 2022-09-20T16:18:11.870 10246: 3418: 3418 I/LSPosed-Bridge ] [yuki][E]--> readOptionFile: No such file or directory
[ 2022-09-20T16:18:12.655 10246: 4102: 4102 I/LSPosed ] Loading xposed for com.qidian.QDReader/10246
[ 2022-09-20T16:18:12.662 10246: 4102: 4102 I/LSPosed-Bridge ] Loading module cn.xihan.qdds from /data/app/cn.xihan.qdds-HuxPU0nRUjCYK4c81btVng==/base.apk
[ 2022-09-20T16:18:12.700 10246: 4102: 4102 I/LSPosed-Bridge ] Loading class cn.xihan.qdds.HookEntryInit
[ 2022-09-20T16:18:12.740 10246: 4102: 4102 I/LSPosed-Bridge ] [YukiHookAPI][E]--> readOptionFile: No such file or directory
```

**Comment by xihan123** [comment]
> > 因为你开启了禁用广告功能
> 
> 已经关闭广告，但是在保存并重启后，设置会恢复默认，并且在LSPosed里面有疑似报错
> 
> ```
> [ 2022-09-20T16:18:11.870 10246: 3418: 3418 I/LSPosed-Bridge ] [yuki][E]--> readOptionFile: No such file or directory
> [ 2022-09-20T16:18:12.655 10246: 4102: 4102 I/LSPosed ] Loading xposed for com.qidian.QDReader/10246
> [ 2022-09-20T16:18:12.662 10246: 4102: 4102 I/LSPosed-Bridge ] Loading module cn.xihan.qdds from /data/app/cn.xihan.qdds-HuxPU0nRUjCYK4c81btVng==/base.apk
> [ 2022-09-20T16:18:12.700 10246: 4102: 4102 I/LSPosed-Bridge ] Loading class cn.xihan.qdds.HookEntryInit
> [ 2022-09-20T16:18:12.740 10246: 4102: 4102 I/LSPosed-Bridge ] [YukiHookAPI][E]--> readOptionFile: No such file or directory
> ```

很明显，没有找到你的配置所在文件夹，你看看根目录是否存在"QDReader"文件夹，创建一个即可

**Comment by xihan123** [comment]
你去看看 README 里面常见问题第一条就是了

**Comment by feilongproject** [comment]
如果关闭禁用TX广告后，那么除了类似看广告有奖励的，其它地方会不会出现无用广告？

**Comment by feilongproject** [comment]
> > 如果关闭禁用TX广告后，那么除了类似看广告有奖励的，其它地方会不会出现无用广告？
> 
> 因为这个是从根本上不允许GDT广告插件加载上，关闭后具体会在哪些地方出现不清楚，

好的，多谢解答
