### ISSUE TITLE
app权限问题

### ISSUE THREAD

**Issue by fxxf1111** [xihan123/QDReadHook#115]
配置文件为什么不放在 app私有目录？sdcard/Android/data.....

网络权限 用来干嘛？
安装app权限 用来干嘛？

**Comment by xihan123** [comment]
> 配置文件为什么不放在 app私有目录？sdcard/Android/data.....
> 
> 网络权限 用来干嘛？ 安装app权限 用来干嘛？

首先Android 10之后私有目录其他应用无权读取(你让起点怎么读取？)
网络权限用来检测模块更新以及隐藏福利列表更新
Android 11 之后读取应用版本号需要安装APP权限
最后说明一点，代码全开源，你看不懂觉得不安全可以不用
