### ISSUE TITLE
配置文件无法生效

### ISSUE THREAD

**Issue by dawn-lc** [xihan123/QDReadHook#12]
https://user-images.githubusercontent.com/30336566/191967393-28ed4d34-f6f4-4afa-a7c2-37e74e9bb252.mp4

**Comment by xihan123** [comment]
先去看看 README 常见问题第一条，试过还不行再说

**Comment by dawn-lc** [comment]
![Screenshot_2022-09-23-21-10-01-766_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/30336566/191967590-037832dc-80b6-43ef-bc54-a3e3be1ffad4.jpg)

**Comment by dawn-lc** [comment]
![Screenshot_2022-09-23-21-11-57-907_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/30336566/191967956-441febff-4f15-4fe5-894e-aea86edc7abf.jpg)

**Comment by dawn-lc** [comment]
> 先去看看 README 常见问题第一条，试过还不行再说

需要给相册权限吗？

**Comment by xihan123** [comment]
> > 先去看看 README 常见问题第一条，试过还不行再说
> 
> 需要给相册权限吗？

不需要，你看看配置文件夹是否存在，不存在就创建一个
