### ISSUE TITLE
app启动图的路径？

### ISSUE THREAD

**Issue by unclefive55** [xihan123/QDReadHook#122]
找了/data/data，0/android/data/com.qidian.QDReader，解压了apk。都没有找到。。。。

**Comment by xihan123** [comment]
什么启动图路径  你打开自定义本地启动图 就会重定向至"/sdcard/Download/QDReader/Splash/"

**Comment by unclefive55** [comment]
> 什么启动图路径  你打开自定义本地启动图 就会重定向至"/sdcard/Download/QDReader/Splash/"

我的意思是，您的这个xp模块不是能破解使用官方付费的启动图么，我想知道这些官方的启动图在哪里能够提取。![Screenshot_2023-09-05-13-23-34-815_com.qidian.QDReader.jpg](https://github.com/xihan123/QDReadHook/assets/80865701/8c48e19d-ac1e-48ba-be03-9c89fc13d28f)

**Comment by xihan123** [comment]
> > 什么启动图路径  你打开自定义本地启动图 就会重定向至"/sdcard/Download/QDReader/Splash/"
> 
> 我的意思是，您的这个xp模块不是能破解使用官方付费的启动图么，我想知道这些官方的启动图在哪里能够提取。![Screenshot_2023-09-05-13-23-34-815_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/80865701/265593496-8c48e19d-ac1e-48ba-be03-9c89fc13d28f.jpg)

抓取后所有图片源链都保存在配置文件中，你找到配置文件用json语法格式化一下就能看到了
