### ISSUE TITLE
[蓝奏云Bug] 目前蓝奏云手机端UA下载会提示开通VIP分享，建议使用zip后缀，下载完再删除等办法

### ISSUE THREAD

**Issue by kermonds** [xihan123/QDReadHook#142]
### 复现步骤

1.打开 https://xihan.lanzouv.com/b0413c6he 
2.点击适合的版本下载

### 预期行为

# 应该会这样
![应该会这样](https://i.imgs.ovh/2023/10/01/VWrIv.jpeg)

### 实际行为

# 实际是这样
![实际是这样](https://i.imgs.ovh/2023/10/01/VWX2W.jpeg)

### LSPosed 版本

6990

### Android 版本

13

### 模块 版本

238

### 起点 版本

1030

### Logs/日志

[question.zip](https://github.com/xihan123/QDReadHook/files/12777149/question.zip)

**Comment by MengNianxiaoyao** [comment]
你手机浏览器ua改成电脑版就行
