### ISSUE TITLE
首次启动直接闪退

### ISSUE THREAD

**Issue by cfeitong** [xihan123/QDReadHook#16]
已经尝试过卸载重装，以及清除所有数据。没啥用。附上[lsp日志](https://drive.google.com/file/d/1-2xvJjPPi2zRSieq_w-O6fxSncTlOhbb/view?usp=drivesdk)

**Comment by xihan123** [comment]
是清除起点的数据，并且后续手动授予起点存储权限，我看日志大概就是没有存储权限。实在不行卸载模块重启手机后再装最新版模块，并重复开头操作

**Comment by xihan123** [comment]
另外再确认一下起点版本是否在模块支持内，部分日志显示找不到类

**Comment by cfeitong** [comment]
清除起点数据的操作没有错，并且赋予了起点储存权限。事实上如果不赋予起点储存权限，反而并不会闪退，只是模块不生效。起点版本是7.9.250_808-335，是从LSPosed repo 中下载的。

**Comment by xihan123** [comment]
你下载错了吧，如果你本身有lsp框架，还下载内置了模块的起点版本，铁定闪退爱。怎么感觉你不是很聪明的亚子

**Comment by cfeitong** [comment]
原来是这样的吗？我还以为这个模块要和patch了的起点配合使用呢。

**Comment by xihan123** [comment]
lsp仓库里面只是额外提供一个已经patch过的版本，因为部分人懒得自己去弄
