### ISSUE TITLE
设置界面一片空白

### ISSUE THREAD

**Issue by 498271674** [xihan123/QDReadHook#17]
昨天装的1.2.3，一开始好好的，今天下午突然间字都不见了，只剩左上角“模块版本1.2.3”和右下角“确定并重启起点”，所有功能都还正常，也能按照正常的位置盲着点进次级界面，次级界面的字是正常的。刚刚更新了1.2.4，也没有好转
![Screenshot_2022-10-01-00-30-18-273_com qidian QDR](https://user-images.githubusercontent.com/38987655/193316887-54ea2491-92e3-42ef-b815-43cc680e4458.jpg)
![Screenshot_2022-10-01-00-32-38-390_com qidian QDR](https://user-images.githubusercontent.com/38987655/193316895-cc6f74d6-599c-4276-92aa-d4a996c19cc0.jpg)

**Comment by xihan123** [comment]
重启应用后依然如此吗

**Comment by 498271674** [comment]
事实上我重启、重装模块、重装起点、换起点版本、换手机字体、换起点字体，都试过了，但是都没用，也不知道是什么奇奇怪怪的bug，也可能是和什么其他模块冲突了。
然后我又出现了新的问题，突然之间没法打开起点了，但是我从lsp把QD模块关闭，能够正常进起点的同时居然还能正常用模块的功能

**Comment by xihan123** [comment]
噗，你是不是用了内置模块的版本+xp模块了，你不是第一这么干的人了
