### ISSUE TITLE
功能

### ISSUE THREAD

**Issue by xwh8965** [xihan123/QDReadHook#170]
哥 请问可以定制一个自己喜欢的功能嘛

**Comment by xihan123** [comment]
？

**Comment by xwh8965** [comment]
我想定制一个模块呢 哈哈可以嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月21日(周二) 上午6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xihan123/QDReadHook] 功能 (Issue #170)




 
？

**Comment by xihan123** [comment]
> 我想定制一个模块呢 哈哈可以嘛
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月21日(周二) 上午6:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xihan123/QDReadHook] 功能 (Issue #170) ？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

说说你的需求和预算

**Comment by xihan123** [comment]
> 是QQ的模块可以嘛&nbsp; 想弄个自己喜欢的小功能
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月21日(周二) 下午3:21 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xihan123/QDReadHook] 功能 (Issue #170) 我想定制一个模块呢 哈哈可以嘛 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年11月21日(周二) 上午6:47 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xihan123/QDReadHook] 功能 (Issue #170) ？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 说说你的需求和预算 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

QQ还是算了  不熟

**Comment by xwh8965** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月21日(周二) 下午3:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xihan123/QDReadHook] 功能 (Issue #170)




  
是QQ的模块可以嘛&nbsp; 想弄个自己喜欢的小功能
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年11月21日(周二) 下午3:21 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xihan123/QDReadHook] 功能 (Issue #170) 我想定制一个模块呢 哈哈可以嘛 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年11月21日(周二) 上午6:47 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xihan123/QDReadHook] 功能 (Issue #170) ？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 说说你的需求和预算 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
QQ还是算了  不熟
