### ISSUE TITLE
求添加功能，隐藏本章说界面打赏小剧场

### ISSUE THREAD

**Issue by 498271674** [xihan123/QDReadHook#20]
![IMG_20221017_191634](https://user-images.githubusercontent.com/38987655/196174857-c1198da2-01a2-4d31-ba9b-6de1a8d28b6f.jpg)
谢谢大佬

**Comment by xihan123** [comment]
这也要隐藏？不知道 Hook 多了会导致应用变卡吗，非必要的我都不想弄的.这个不是刚需，等我有空吧

**Comment by xihan123** [comment]
1.2.8已更新

**Comment by 498271674** [comment]
你是我的神
