### ISSUE TITLE
免责声明倒计时异常

### ISSUE THREAD

**Issue by by123456by** [xihan123/QDReadHook#206]
### 复现步骤

包含模块设置，没有进入模块设置界面

### 预期行为

接受协议并进入设置

### 实际行为

![Screenshot_2024-03-02-11-38-32-903_com qidian QDReader](https://github.com/xihan123/QDReadHook/assets/15666692/ad84a25a-4863-4dde-a01b-6813bb5d1ded)
没有看到接受的按钮

### LSPosed 版本

7058

### Android 版本

14

### 模块 版本

3.1.0

### 起点 版本

7.9.334

### Logs/日志

无法进入设置，无法提供

**Comment by xihan123** [comment]
你的意思是这个倒计时不动是吗，点标题就可以归零了。倒计时不动的问题预计下个版本修复

**Comment by by123456by** [comment]
> 你的意思是这个倒计时不动是吗，点标题就可以归零了。倒计时不动的问题预计下个版本修复

这里有倒计时吗，他不动的，我还等了好久，已经进来了，谢谢
