### ISSUE TITLE
设置选项启用后重启不管用

### ISSUE THREAD

**Issue by daofeng2015** [xihan123/QDReadHook#21]
![Screenshot_2022-10-23-11-37-50-518_com qidian QDReader](https://user-images.githubusercontent.com/14891398/197372309-76e12845-8940-4acd-b1bc-cf4c35af1a1d.jpg)
![Screenshot_2022-10-23-11-37-37-608_com qidian QDReader](https://user-images.githubusercontent.com/14891398/197372323-6d15e8db-5bd0-4290-98d0-7e39aa851a41.jpg)
清楚全部数据也一样

**Comment by xihan123** [comment]
给起点存储权限没

**Comment by xihan123** [comment]
还有lspatch 和模块只能用一个

**Comment by daofeng2015** [comment]
> 给起点存储权限没，查看/sdcard/Download/QDReader 目录是否存在，是否有数据

没看到这个目录 lspatch是和阿b客户端用的那个吧

**Comment by daofeng2015** [comment]
解决了,手动授予存储权限重启就🆗了,要是能触发权限授予的页面那就更好了
