### ISSUE TITLE
作者你好，不知道能不能设置个开关，以便于开启或关闭章节结尾出现的看视频领奖励的按钮啊？

### ISSUE THREAD

**Issue by TushningJJ** [xihan123/QDReadHook#22]
![Screenshot_2022-10-27-17-25-37-901-edit_com android browser](https://user-images.githubusercontent.com/9523144/198247369-48b7023c-ff33-4310-bce1-081686d10694.jpg)
就是这个，如果有开关可以关闭这个东西就好了

**Comment by TushningJJ** [comment]
> 

视频奖励

**Comment by xihan123** [comment]
等我有空

**Comment by TushningJJ** [comment]
> 等我有空

好的，谢谢

**Comment by xihan123** [comment]
1.2.9版本已解决

**Comment by TushningJJ** [comment]
> 1.2.9版本已解决

好的，谢谢
