### ISSUE TITLE
[Feature Request] 关于模块的配置文件的存储路径的建议，（ps：我只是建议）

### ISSUE THREAD

**Issue by hzy132** [xihan123/QDReadHook#225]
### 你的请求是否与某个问题相关？

作者您好，模块的配置文件目前存储在Download文件夹下

### 描述你想要的解决方案

作者您好，我参考其他一些xp模块的做法给出建议，将模块配置文件存储在起点app的私有目录里：

在模块app中不提供查看和修改配置文件的界面，只提供：①如何在起点app中进入模块功能设置的文字提示、②隐藏模块桌面图标的选项、③模块的关于信息。
将模块配置文件存储在起点app的私有目录里，和之前一样的 在起点app的设置中提供模块功能设置，并在起点app的模块功能设置里添加通过SAF框架来备份配置文件的选项，这里过程就不需要申请相关存储权限。

**Comment by xihan123** [comment]
> ### 你的请求是否与某个问题相关？
> 作者您好，模块的配置文件目前存储在Download文件夹下
> 
> ### 描述你想要的解决方案
> 作者您好，我参考其他一些xp模块的做法给出建议，将模块配置文件存储在起点app的私有目录里：
> 
> 在模块app中不提供查看和修改配置文件的界面，只提供：①如何在起点app中进入模块功能设置的文字提示、②隐藏模块桌面图标的选项、③模块的关于信息。 将模块配置文件存储在起点app的私有目录里，和之前一样的 在起点app的设置中提供模块功能设置，并在起点app的模块功能设置里添加通过SAF框架来备份配置文件的选项，这里过程就不需要申请相关存储权限。
> 
> ### 其他信息
> _No response_

其实这个问题考虑过，如果放在了私有目录，是不是多开和共存就很方便了?(薅羊毛的多了模块似的更快)
现在强制外部存储从某种层面上限制了一部设备最多2个左右的号
因为之前某个模块事件弄的现在我不敢做出更多的改变。
要做可以自己fork过去编译，但是注意后果自负。
当然最大的可能还是这个项目一起GG
