### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 498271674** [xihan123/QDReadHook#23]
勾选“主页底部导航栏红点”，不勾选“主页底部导航栏发现”，会把发现一同隐藏，这是bug吗？
![Screenshot_2022-10-29-19-34-55-069_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/38987655/198829247-05b9a186-54dd-4e84-9e07-802030326b96.jpg)![Screenshot_2022-10-29-19-35-07-409_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/38987655/198829250-68662ac7-010d-451c-81e7-28d3c7320dd6.jpg)

**Comment by 498271674** [comment]
又试了试，发现是两个选项功能反了

**Comment by xihan123** [comment]
我的锅，我把红点和发现的Hook搞反了，写阅读页功能的时候看的眼花了

**Comment by xihan123** [comment]
重新打包了一下，你重新下载试试
