### ISSUE TITLE
自动签到失效

### ISSUE THREAD

**Issue by 498271674** [xihan123/QDReadHook#25]
其实已经失效三个版本了，前两天更新了一下起点，2号凌晨忽然发现自动签到失效了，下了上个版本，但是当天已经签过到了没法验证，刚刚过3号0点了试了试，上版本也没自动签到，想来报bug发现又更了新版本，遂下载最新版本，但最新版本也没给自动签🤔

**Comment by 498271674** [comment]
试了一下发现启用旧版书架布局也无效，不会是我的问题吧😧不过其他功能好像都正常

**Comment by 498271674** [comment]
![Screenshot_2022-12-03-00-26-24-039_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/38987655/205339193-2fdc803f-6752-4e61-8e12-c95f0cf1afe3.jpg)![Screenshot_2022-12-03-00-26-46-545_com.qidian.QDReader.jpg](https://user-images.githubusercontent.com/38987655/205339252-ed0742fa-2706-4535-9d21-9febff20bc0c.jpg)

**Comment by xihan123** [comment]
我这测试正常，你看看有没有日志  是不是版本不对？

**Comment by 498271674** [comment]
😓原来是我开了禁用检查更新，设置关于里面不显示有新版本我一直以为我是最新版本，一会十二点过了我再看看签到正常不

另外更新起点之后，模块主设置条目里面少了三个选项，是功能取消了么

**Comment by xihan123** [comment]
> 😓原来是我开了禁用检查更新，设置关于里面不显示有新版本我一直以为我是最新版本，一会十二点过了我再看看签到正常不
> 
> 另外更新起点之后，模块主设置条目里面少了三个选项，是功能取消了么

> 用最新模块 少了选项应该是我忘记调高版本了 可暂时先用起点842版本
