### ISSUE TITLE
你好，请问可不可以做到去广告领奖励

### ISSUE THREAD

**Issue by Cliencer** [xihan123/QDReadHook#26]
![Screenshot_20221211-214241](https://user-images.githubusercontent.com/79413453/206907257-db797e0a-f08e-42eb-a203-6731d3e5e411.png)
如图这里的广告每天可以看10个，能不能把它们去掉直接领奖励。目前广告是去干净了但是奖励也领取不了了

**Comment by Cliencer** [comment]
如果不可以的话能不能弄一个自动化的小插件，可以自动看视频那种，，，

**Comment by xihan123** [comment]
理论上可行，等我有空试试吧

**Comment by Cliencer** [comment]
> 理论上可行，等我有空试试吧

抓住作者在线催更新，顺便问问有没有群~

**Comment by xihan123** [comment]
> > 理论上可行，等我有空试试吧
> 
> 抓住作者在线催更新，顺便问问有没有群~

群的话我创一个就是了:727983520

**Comment by Cliencer** [comment]
> > > 理论上可行，等我有空试试吧
> > 
> > 
> > 抓住作者在线催更新，顺便问问有没有群~
> 
> 群的话我创一个就是了:727983520

已加群，望通过，另外打赏10.24不成敬意
