### ISSUE TITLE
在zygisk下日志报错无法启动

### ISSUE THREAD

**Issue by as614001** [xihan123/QDReadHook#27]

**Comment by xihan123** [comment]
?这是XP模块  跟zygisk有什么关系

**Comment by as614001** [comment]
切换到zygisk注入就会报错，riru注入没问题，看日志是提示找不到类。可能是你引用的hook框架的问题吧。

**Comment by as614001** [comment]
> ?这是XP模块 跟zygisk有什么关系

failed load claskk cn.xihan.qdds.HookEntryInit

**Comment by xihan123** [comment]
> > ?这是XP模块 跟zygisk有什么关系
> 
> failed load class cn.xihan.qdds.HookEntryInit

用的什么版本 包括xp框架和模块版本说一下

**Comment by as614001** [comment]
magisk25.2（zygisk注入）+ LSPOSED1.8.5 + 模块最新版  +起点850

**Comment by xihan123** [comment]
> magisk25.2（zygisk注入）+ LSPOSED1.8.5 + 模块最新版 +起点850

退回前几个版本试试？虽然会不支持最新版  亦或者用lspatch修补试试 看看哪的问题 找不到入口 不应该单你出现问题
