### ISSUE TITLE
完蛋了，账号异常了。

### ISSUE THREAD

**Issue by wengzhenquan** [xihan123/QDReadHook#270]
### 复现步骤

跳过广告领取福利奖励，提示账号异常。
试了几个账号都不行了。
不会有封号风险吧？
![Screenshot_2024-07-20-00-17-15-715_com qidian QDReader](https://github.com/user-attachments/assets/8e9ae462-dc90-49dd-8bc8-b4c763f89e8d)

### 预期行为

领取成功

### 实际行为

账号异常

### LSPosed 版本

7058

### Android 版本

11

### 模块 版本

3.2.0

### 起点 版本

7.9.358

### Logs/日志

反应个问题好麻烦啊，难怪issue空荡荡的

**Comment by xihan123** [comment]
首先你要明白你是被检测ROOT还是福利中心高风险，这个提示和模块无关

**Comment by wengzhenquan** [comment]
突然又恢复了，肯定不是root检测，这过程中没动过环境。
也许是阅文那边的问题
