### ISSUE TITLE
每日福利，最后一个奖励（阅读币），视频广告无法跳过

### ISSUE THREAD

**Issue by wengzhenquan** [xihan123/QDReadHook#271]
### 你的请求是否与某个问题相关？

如果调用手机QQ，使用QQ账号登录，每日福利20章节卡后面会多出一个4阅读币的奖励，点击领取，没有像前面的奖励那样跳过15秒视频广告
![IMG_20240723_180222](https://github.com/user-attachments/assets/8dba5724-0ef2-4804-878f-2bc5952fcf77)

### 描述你想要的解决方案

把前面跳过广告的解决方法，复用在最后一个阅读币上，加一个if判断就行了

### 其他信息

必须用QQ登录才会出现阅读币奖励
![IMG_20240723_180605](https://github.com/user-attachments/assets/cbe1c94b-25c1-4d73-9bc1-db52bc51bc69)

**Comment by xihan123** [comment]
最后一个视频无法跳过确实是个问题，目前还没去分析
另外如果你觉得解决方案那么简单实现就请提个PR

**Comment by xihan123** [comment]
补充一点信息
你起点和模块版本是多少？

**Comment by xihan123** [comment]
或者可以抓包一下福利中心mainPage这个接口的内容提供给我?

**Comment by wengzhenquan** [comment]
起点版本：7.9.358
模块版本：3.2.0-545

**Comment by xihan123** [comment]
没法提供更多信息那我也没辙啊，我没有号有第九个
另外可以自动化领

**Comment by wengzhenquan** [comment]
你没发用qq号登录吗？
我记得没错的话，好几个版本都是这样的效果，毕竟模块我也用了几个月了，更新几次了。
极有可能不是个别版本的。你用qq登录就能复现了

**Comment by xihan123** [comment]
你在说什么，我的意思是我没有第九个奖励的账号
和登录方式有什么关系

**Comment by wengzhenquan** [comment]
前面我说了，用qq号登录，才有那个奖励

**Comment by xihan123** [comment]
前面我说了，和登录方式无关，第九个奖励只有部分账号有

**Comment by wengzhenquan** [comment]
QQ：1340503918
密码：wzq12648103
一会儿我回复你手机验证码

**Comment by xihan123** [comment]
别发出来，另外我已经在测试了，目前来看没有什么特别有效的办法

**Comment by wengzhenquan** [comment]
这就很奇怪了，我两个QQ号登录都有第九个奖励。。。

**Comment by xihan123** [comment]
分析完成了，第九个广告是完全网页实现的，没有调用SDK，该问题暂时无法解决

**Comment by wengzhenquan** [comment]
好吧，辛苦了
