### ISSUE TITLE
设备多账号解锁

### ISSUE THREAD

**Issue by wengzhenquan** [xihan123/QDReadHook#276]
### 你的请求是否与某个问题相关？

此前没有这个问题，今天突然出现的。
多个账号领取奖励，突然出现这个提示。
能否解决？
![Screenshot_2024-07-26-20-11-06-372_com qidian QDReader](https://github.com/user-attachments/assets/3c40dc4b-c074-4674-9afe-3c510db6f3d1)

### 描述你想要的解决方案

不知道呀。

**Comment by xihan123** [comment]
善用模块功能，这个问题非模块问题，即将关闭

**Comment by wengzhenquan** [comment]
我提交的不是bug啊，当然不是模块问题。
哎，算了。。。不能支持就不能支持吧。。

**Comment by wengzhenquan** [comment]
解决了？找不到呀！
不是今天才出现的问题吗？为什么八年前就解决了？
此前我几个账号轮流切，都没这个问题。
另外，这个项目都八年以上了？

**Comment by xihan123** [comment]
洗洗睡吧 别再折腾了

**Comment by wengzhenquan** [comment]
说的话，好难懂啊😓，说了这么多，就是没谈这个问题怎么解决，或者哪个功能能够解决。

**Comment by xihan123** [comment]
因为只有聪明人才知道  就是谜语人  就是玩

**Comment by wengzhenquan** [comment]
所以，你肯定是有病的吧？
咱本来就是就事论事，有问题问问题，没问题也没兴趣跟你闲聊。
有病的话就去治吧。

**Comment by xihan123** [comment]
我最开始就回答了你的问题，是你一直无法理解，并且一直重复问好吗
还有你的语气，你是甲方吗，我给你办事的是吗

**Comment by wengzhenquan** [comment]
咱就是真诚的发问，结果被人戏耍，连尊重都学不会。
“善用模块”能解决问题吗？模块里面有这个功能吗？我前面也说了，
“我提交的不是bug啊，当然不是模块问题。
哎，算了。。。不能支持就不能支持吧。”

在模块里面，有“善用模块”这个文案的字眼吗？对应那一块功能？

**Comment by wengzhenquan** [comment]
不回了，遇到喜欢戏耍人的，不懂得尊重的，惹不起，我躲得起。

**Comment by xihan123** [comment]
你的意思是要我直接在这公开论坛里面直接公布解决方案，然后让起点封堵这个漏洞是吗
你连模块的功能都没研究明白，怎么就知道模块不能解决这个问题呢？

**Comment by xihan123** [comment]
你但凡在别的地方比如群聊  早就直接回答你了
非要在这用甲方语气给我一顿质问 
我为爱发电开发两年多是拿了你一分钱工资吗？
