### ISSUE TITLE
书架内限免书籍支持自动下载

### ISSUE THREAD

**Issue by a76yyyy** [xihan123/QDReadHook#28]
![Screenshot_2023-01-06-13-10-42-729_com qidian QDReader](https://user-images.githubusercontent.com/56478790/210934547-b8c00bf2-5013-492a-b534-1b26be5e7947.jpg)
如图，限免书籍不能批量下载

**Comment by xihan123** [comment]
等我有空看看

**Comment by xihan123** [comment]
已经实现了，目前群里内测，你可以加群下载体验一下，正式版推送时间不定
