### ISSUE TITLE
[Bug] 用不了

### ISSUE THREAD

**Issue by yuf19-2022** [xihan123/QDReadHook#297]
### 复现步骤

集成模块

### 预期行为

打开软件

### 实际行为

软件打不开

### LSPosed 版本

lspatch0.6

### Android 版本

android14

### 模块 版本

3.23

### 起点 版本

7.9.366，以前的起点版本我就试过了，旧手机iqoo u1可以，现在的手机是iqoo neo8 pro不行

### Logs/日志

无

**Comment by xihan123** [comment]
说明一下你是如何制作内置的，能提供录屏就更好了

还有就不要用默认的内置签名

**Comment by xihan123** [comment]
> > 说明一下您是如何制作内置的，能够提供录屏就更好了
> > 还有不会使用默认的内置签名
> 
> 我找别人要了一份集成好的可以用了，可能我集成的有问题吧，以前那个手机就是那样集成的都没问题

那就是你自己的问题噻，你不会是勾选了可调试吧？

**Comment by xihan123** [comment]
可调试和覆写版本号都不用勾

**Comment by ypq123456789** [comment]
> lspatch0.6


老哥您好，不好意思打扰了，方便私发我一份集成好的吗？我也是集成了用不了，谢谢谢谢 648558021@qq.com

**Comment by ypq123456789** [comment]
> > > > 说明一下您是如何制作内置的，能够提供录屏就更好了
> > > > 还有不会使用默认的内置签名
> > > 
> > > 
> > > 我找别人要了一个集成好的可以用了，可能我集成的有问题吧，以前那个手机就是那样集成的都没有问题
> > 
> > 
> > 那就是你自己的问题噻，你不会是勾选了可调试吧？
> 
> 原来我都是勾选的，可调式，覆写版本号，旧手机都可以的，新手机不行最后我没勾选也不行

我发现就是勾选可调试和覆写版本号导致的，不勾选就好了

**Comment by ypq123456789** [comment]
是的大佬，可以了，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月2日(周六) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xihan123/QDReadHook] [Bug] 用不了 (Issue #297)




      
说明一下您是如何制作内置的，能够提供录屏就更好了
 还有不会使用默认的内置签名
  
我找别人要了一个集成好的可以用了，可能我集成的有问题吧，以前那个手机就是那样集成的都没有问题
  
那就是你自己的问题噻，你不会是勾选了可调试吧？
  
原来我都是勾选的，可调式，覆写版本号，旧手机都可以的，新手机不行最后我没勾选也不行
  
我发现就是勾选可调试和覆写版本号导致的，不勾选就好了
  
就是说OK了是吗？
