### ISSUE TITLE
2.1.2失效

### ISSUE THREAD

**Issue by SugarFatFree** [xihan123/QDReadHook#34]
2.1.2很多配置都不生效，比如隐藏“我的”里面的一些东西，我切换到原来的2.1.1是生效的；还有就是“免广告领取奖励”都失效了，原来2.1.1是生效的，后来更新到2.1.2失效，再然后我卸载，删配置文件，重启，安装会2.1.1还是不生效，希望能修复下。

**Comment by xihan123** [comment]
> 2.1.2很多配置都不生效，比如隐藏“我的”里面的一些东西，我切换到原来的2.1.1是生效的；还有就是“免广告领取奖励”都失效了，原来2.1.1是生效的，后来更新到2.1.2失效，再然后我卸载，删配置文件，重启，安装会2.1.1还是不生效，希望能修复下。

？你是不是起点更新到不支持的版本了

**Comment by SugarFatFree** [comment]
> > 2.1.2很多配置都不生效，比如隐藏“我的”里面的一些东西，我切换到原来的2.1.1是生效的；还有就是“免广告领取奖励”都失效了，原来2.1.1是生效的，后来更新到2.1.2失效，再然后我卸载，删配置文件，重启，安装会2.1.1还是不生效，希望能修复下。
> 
> ？你是不是起点更新到不支持的版本了

恢复到2.1.1版本后，净化-我-隐藏控件 是生效的，但是2.1.2是不生效的。

**Comment by xihan123** [comment]
> > > 2.1.2很多配置都不生效，比如隐藏“我的”里面的一些东西，我切换到原来的2.1.1是生效的；还有就是“免广告领取奖励”都失效了，原来2.1.1是生效的，后来更新到2.1.2失效，再然后我卸载，删配置文件，重启，安装会2.1.1还是不生效，希望能修复下。
> > 
> > 
> > ？你是不是起点更新到不支持的版本了
> 
> 恢复到2.1.1版本后，净化-我-隐藏控件 是生效的，但是2.1.2是不生效的。

你起点版本不说我咋知道你啥版本？
