### ISSUE TITLE
赞赏了10.24，可以考虑做个内置版本吗

### ISSUE THREAD

**Issue by clbclby** [xihan123/QDReadHook#4]
在酷安发不了言，号已经黑了，只能在这说了。模块做的很不错，尽管目前我还用不了，因为尝试内置一直不成功，可能是没有root吧，或者是其它原因，希望您可以考虑做个内置版本的，多谢您！未来可追已经打赏10.24元支持一下，谢谢你的项目，让看正版网文有了该有的体验！

**Comment by xihan123** [comment]
已发在蓝奏云，快去下载使用吧，记得看说明
