### ISSUE TITLE
可否考虑增加精简布局，隐藏部分内容

### ISSUE THREAD

**Issue by clbclby** [xihan123/QDReadHook#5]
最新内置版本完美运行，功能正常。如果可以设置隐藏一部分内容就更好了。比如每日导读部分，底部发现栏部分，我的页面布局精简。章节末尾看视频领点币横幅也可以去掉，目前体验已经很棒了，这些也算是锦上添花吧。衷心感谢您的工作！支持！

**Comment by xihan123** [comment]
已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧

**Comment by clbclby** [comment]
> 已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧

谢谢，尝试了下最新内置版本，在此之前，我是把内置版本卸载后重新安装的，也把最新的配置文件放到/storage/emulated/0/Android/QDReader里面了，安装完成之后，打开应用之前也已经打开了存储权限。不过隐藏布局功能似乎没有生效，包括隐藏发现和我的页面的功能。选好隐藏布局之后，点击重启，重新打开之后发现回到了原先未选择的配置，隐藏功能均未生效。如果可以把每日导读，搜索页面的搜索发现，热搜，为你推荐也隐藏掉就更好了。您辛苦了，多谢您！

**Comment by xihan123** [comment]
> > 已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧
> 
> 谢谢，尝试了下最新内置版本，在此之前，我是把内置版本卸载后重新安装的，也把最新的配置文件放到/storage/emulated/0/Android/QDReader里面了，安装完成之后，打开应用之前也已经打开了存储权限。不过隐藏布局功能似乎没有生效，包括隐藏发现和我的页面的功能。选好隐藏布局之后，点击重启，重新打开之后发现回到了原先未选择的配置，隐藏功能均未生效。如果可以把每日导读，搜索页面的搜索发现，热搜，为你推荐也隐藏掉就更好了。您辛苦了，多谢您！

你路径搞错了，选项当然不生效，我在说明文档里面提过"/sdcard/QDReader"、"/storage/emulated/0/QDReader/"不同版本显示的可能不一样，其实可以理解为外置存储的根目录。

**Comment by clbclby** [comment]
> > > 已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧
> > 
> > 
> > 谢谢，尝试了下最新内置版本，在此之前，我是把内置版本卸载后重新安装的，也把最新的配置文件放到/storage/emulated/0/Android/QDReader里面了，安装完成之后，打开应用之前也已经打开了存储权限。不过隐藏布局功能似乎没有生效，包括隐藏发现和我的页面的功能。选好隐藏布局之后，点击重启，重新打开之后发现回到了原先未选择的配置，隐藏功能均未生效。如果可以把每日导读，搜索页面的搜索发现，热搜，为你推荐也隐藏掉就更好了。您辛苦了，多谢您！
> 
> 你路径搞错了，选项当然不生效，我在说明文档里面提过"/sdcard/QDReader"、"/storage/emulated/0/QDReader/"不同版本显示的可能不一样，其实可以理解为外置存储的根目录。

实在不好意思，的确是我搞错了，经测试隐藏布局功能一切正常，不过我的页面中间区域出现一片空白，其它均没有问题。不过若是把每日导读，搜索页面的布局也隐藏掉应该挺好的。尤其是每日导读推的书很不准确，搜索页面挂的也是排名靠前爆款书。感谢作者，您辛苦了！一直支持，加油！

**Comment by xihan123** [comment]
> > > > 已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧
> > > 
> > > 
> > > 谢谢，尝试了下最新内置版本，在此之前，我是把内置版本卸载后重新安装的，也把最新的配置文件放到/storage/emulated/0/Android/QDReader里面了，安装完成之后，打开应用之前也已经打开了存储权限。不过隐藏布局功能似乎没有生效，包括隐藏发现和我的页面的功能。选好隐藏布局之后，点击重启，重新打开之后发现回到了原先未选择的配置，隐藏功能均未生效。如果可以把每日导读，搜索页面的搜索发现，热搜，为你推荐也隐藏掉就更好了。您辛苦了，多谢您！
> > 
> > 
> > 你路径搞错了，选项当然不生效，我在说明文档里面提过"/sdcard/QDReader"、"/storage/emulated/0/QDReader/"不同版本显示的可能不一样，其实可以理解为外置存储的根目录。
> 
> 实在不好意思，的确是我搞错了，经测试隐藏布局功能一切正常，不过我的页面中间区域出现一片空白，其它均没有问题。不过若是把每日导读，搜索页面的布局也隐藏掉应该挺好的。尤其是每日导读推的书很不准确，搜索页面挂的也是排名靠前爆款书。感谢作者，您辛苦了！一直支持，加油！

114版本搜索一刀切了，你可以试试，另外每日导读其实没必要搞，因为你只要不去点开就行，如果要从模块层面去除有点麻烦

**Comment by clbclby** [comment]
> > > > > 已完成，章节末尾看视频领点币横幅我没看见，等看见了再说吧
> > > > 
> > > > 
> > > > 谢谢，尝试了下最新内置版本，在此之前，我是把内置版本卸载后重新安装的，也把最新的配置文件放到/storage/emulated/0/Android/QDReader里面了，安装完成之后，打开应用之前也已经打开了存储权限。不过隐藏布局功能似乎没有生效，包括隐藏发现和我的页面的功能。选好隐藏布局之后，点击重启，重新打开之后发现回到了原先未选择的配置，隐藏功能均未生效。如果可以把每日导读，搜索页面的搜索发现，热搜，为你推荐也隐藏掉就更好了。您辛苦了，多谢您！
> > > 
> > > 
> > > 你路径搞错了，选项当然不生效，我在说明文档里面提过"/sdcard/QDReader"、"/storage/emulated/0/QDReader/"不同版本显示的可能不一样，其实可以理解为外置存储的根目录。
> > 
> > 
> > 实在不好意思，的确是我搞错了，经测试隐藏布局功能一切正常，不过我的页面中间区域出现一片空白，其它均没有问题。不过若是把每日导读，搜索页面的布局也隐藏掉应该挺好的。尤其是每日导读推的书很不准确，搜索页面挂的也是排名靠前爆款书。感谢作者，您辛苦了！一直支持，加油！
> 
> 114版本搜索一刀切了，你可以试试，另外每日导读其实没必要搞，因为你只要不去点开就行，如果要从模块层面去除有点麻烦

谢谢，主要是每日导读和搜索栏关键词滚动播放有点频繁，还有点卡顿，不去掉也没什么问题。目前体验已经很完美了，辛苦啦！
