### ISSUE TITLE
崩溃 xp模块和xpatch版本都是

### ISSUE THREAD

**Issue by intellp** [xihan123/QDReadHook#7]
显示空指针

**Comment by xihan123** [comment]
版本以及日志贴一下

**Comment by intellp** [comment]
疑似是桌面启动时，不能正常启动相应的activity 使用长摁等快捷方式可以正常启动

**Comment by xihan123** [comment]
> 疑似是桌面启动时，不能正常启动相应的activity 使用长摁等快捷方式可以正常启动

使用前清除一下起点数据试过吗

**Comment by intellp** [comment]
卸载了重装 ok了
