### ISSUE TITLE
无法关闭禁用腾讯广告

### ISSUE THREAD

**Issue by CuteLittleSky** [xihan123/QDReadHook#8]
已测试清除应用数据(起点,QD模块)无效
话说那个看广告领点币的选项应该和这个有关吧，

**Comment by CuteLittleSky** [comment]
![Screenshot_2022-09-10-13-40-11-52_d2d2e5afa7e0f03725be661ee68060ea](https://user-images.githubusercontent.com/62592731/189470885-5a19f254-4d14-4eb3-9d4c-cfb5b8473be9.jpg)
7.9.242

**Comment by xihan123** [comment]
你仔细看README文档了吗，选项修改不生效都是因为你配置文件夹不存在，去创建一个就行了

**Comment by CuteLittleSky** [comment]
抱歉，我的锅，谢谢大佬了
但禁用腾讯广告后看小视频领奖励是无法加载广告的:
